name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test_tracker:

    runs-on: ubuntu-latest

    steps:
    - name: Install libpcap
      run: sudo apt-get install libpcap-dev

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    
    - name: Get repository code
      uses: actions/checkout@v3
    
    - name: Build qmake-file
      run: cd ./TrackerProgram/TestTracker/ && qmake TestTracker.pro
    
    - name: Create executable file
      run: cd ./TrackerProgram/TestTracker/ && make

    - name: Run test filters
      run: cd ./TrackerProgram/TestTracker/ && ./TestTracker
